SELECT * FROM potro_clinica.citas;
SELECT * FROM potro_clinica.medicos;
SELECT * FROM potro_clinica.pacientes;
SELECT * FROM potro_clinica.consultas;
SELECT * FROM potro_clinica.citas_emergencia;
SELECT * FROM potro_clinica.citas_previas;
SELECT * FROM potro_clinica.usuarios;
SELECT * FROM horarios_medicos;
select * from usuarios where usuario = "amlo@gmail.com";
UPDATE USUARIOS SET CONTRASENIA = "akjAAQI893" WHERE USUARIO = "amlo@gmail.com";
SELECT * FROM HISTORIAL_CITAS_PACIENTES;
UPDATE USUARIOS SET CONTRASENIA = "abcKAF648" WHERE USUARIO = "neto@hotmail.com";
SELECT * FROM CITAS_EMERGENCIA WHERE ID_CITA_EMERGENCIA = 3 AND FOLIO = 80068587;

UPDATE CITAS_EMERGENCIA SET ESTADO = "No atendida" WHERE ID_CITA_EMERGENCIA = 1;
UPDATE CITAS_PREVIAS SET ESTADO = "No atendida" WHERE ID_CITA_PREVIA = 6;

CALL REGISTRAR_CONSULTA(
	"Hola",
    "Ya estoy harto de dar ejemplos",
    "Pelota",
    1);
    
SELECT
  ID,
  NOMBRES,
  APELLIDO_PATERNO,
  APELLIDO_MATERNO,
  ESPECIALIDAD,
  ESTADO
FROM DATOS_MEDICO
WHERE USUARIO = '113259' AND CONTRASENIA = 'JbiIUbKBk';
UPDATE USUARIOS SET CONTRASENIA = "AHDjdjasj678" WHERE ID = 3;

SELECT DISTINCT
	M.ID_MEDICO,
	M.NOMBRES,
    M.APELLIDO_PATERNO,
    M.APELLIDO_MATERNO,
    M.ESPECIALIDAD,
    M.ESTADO
FROM MEDICOS AS M
INNER JOIN USUARIOS AS U
ON M.ID_MEDICO = U.ID
INNER JOIN CITAS AS C
ON C.ID_MEDICO = M.ID_MEDICO
WHERE C.FECHA_HORA != "2025-03-04 10:00"
AND ESPECIALIDAD = "Medicina General";
