-- Creación de la base de datos.
CREATE DATABASE IF NOT EXISTS POTRO_CLINICA;

-- Uso de la base de datos
USE POTRO_CLINICA;

-- Creación de tabla USUARIOS.
CREATE TABLE IF NOT EXISTS USUARIOS(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    USUARIO VARCHAR(150) NOT NULL UNIQUE,
    CONTRASENIA VARCHAR(128) NOT NULL,
    ROL ENUM("Medico", "Paciente") NOT NULL
);

-- Creación de tabla MEDICOS. Especialización con USUARIOS.
CREATE TABLE IF NOT EXISTS MEDICOS(
	ID_MEDICO INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(100) NOT NULL,
    ESPECIALIDAD VARCHAR(50) NOT NULL,
    ESTADO ENUM("Alta", "Baja") NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES USUARIOS(ID) -- Llave foránea con USUARIOS
);

-- Creación de tabla HORARIOS_MEDICOS.
CREATE TABLE IF NOT EXISTS HORARIOS_MEDICOS(
	ID_HORARIO INT PRIMARY KEY AUTO_INCREMENT,
    DIA_SEMANA ENUM("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday") NOT NULL,
    HORA_ENTRADA TIME NOT NULL,
    HORA_SALIDA TIME NOT NULL,
    ID_MEDICO INT NOT NULL,
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

-- Creación de tabla PACIENTES. Especialización con USUARIOS:
CREATE TABLE IF NOT EXISTS PACIENTES(
	ID_PACIENTE INT PRIMARY KEY AUTO_INCREMENT,
    NOMBRES VARCHAR(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR(100) NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL UNIQUE,
    FECHA_NACIMIENTO DATE NOT NULL,
    ESTADO ENUM("Alta", "Baja") NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES USUARIOS(ID)
);

-- Creación de tabla DIRECCIONES. Guarda las direcciones de los pacientes.
CREATE TABLE IF NOT EXISTS DIRECCIONES(
	ID_DIRECCION INT PRIMARY KEY AUTO_INCREMENT,
    COLONIA VARCHAR(100) NOT NULL,
    CALLE VARCHAR(100) NOT NULL,
    NUMERO VARCHAR(20) NOT NULL,
    ID_PACIENTE INT NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE)
);

-- Creación de tabla CITAS. Relaciona a medicos con pacientes.
CREATE TABLE IF NOT EXISTS CITAS(
	ID_CITA INT PRIMARY KEY AUTO_INCREMENT,
    FECHA_HORA DATETIME NOT NULL,
    TIPO_CITA ENUM("Previa", "Emergencia") NOT NULL,
    ID_MEDICO INT NOT NULL,
    ID_PACIENTE INT NOT NULL,
    FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTES(ID_PACIENTE),
    FOREIGN KEY (ID_MEDICO) REFERENCES MEDICOS(ID_MEDICO)
);

-- Creación de tabla CITAS_MEDICAS. Especialización con CITAS.
CREATE TABLE IF NOT EXISTS CITAS_PREVIAS(
	ID_CITA_PREVIA INT PRIMARY KEY,
    ESTADO ENUM("Atendida", "Cancelada", "No atendida") NOT NULL DEFAULT "No atendida",
    FOREIGN KEY (ID_CITA_PREVIA) REFERENCES CITAS(ID_CITA)
);

-- Creación de tabla CITAS_EMERGENCIA. Especialización con CITAS.
CREATE TABLE IF NOT EXISTS CITAS_EMERGENCIA(
	ID_CITA_EMERGENCIA INT PRIMARY KEY,
    ESTADO ENUM("Atendida", "No atendida") NOT NULL DEFAULT "No atendida",
    FOLIO INT NOT NULL,
    FOREIGN KEY (ID_CITA_EMERGENCIA) REFERENCES CITAS(ID_CITA)
);

-- Creacion de tablas AUDITORIAS. Registra el cambio en los estados de las citas.
CREATE TABLE IF NOT EXISTS AUDITORIA_CITAS(
	ID_AUDITORIA INT PRIMARY KEY AUTO_INCREMENT,
    FECHA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ESTADO_ANTERIOR ENUM("Atendida", "Cancelada", "No atendida") NOT NULL,
    ESTADO_NUEVO ENUM("Atendida", "Cancelada", "No atendida") NOT NULL,
    ID_CITA INT NOT NULL,
    FOREIGN KEY (ID_CITA) REFERENCES CITAS(ID_CITA)
);

-- Creación de tabla CONSULTAS.
CREATE TABLE IF NOT EXISTS CONSULTAS(
	ID_CONSULTA INT PRIMARY KEY AUTO_INCREMENT,
    MOTIVO VARCHAR(100) NOT NULL,
    DIAGNOSTICO TEXT NOT NULL,
    TRATAMIENTO TEXT NOT NULL,
    ID_CITA INT NOT NULL,
    FOREIGN KEY (ID_CITA) REFERENCES CITAS(ID_CITA)
);