/*
	Vista que muestra el historial de consultas de un paciente,
    tanto por especialidad del médico, un rango de fechas
    y un paciente en específico.
*/
CREATE VIEW HISTORIAL_CONSULTAS_PACIENTES AS
SELECT
	C.ID_CONSULTA,
    CT.ID_CITA,
    CT.ID_MEDICO,
    M.NOMBRES AS NOMBRE_MEDICO,
    M.APELLIDO_PATERNO AS APELLIDO_PATERNO_MEDICO,
    M.APELLIDO_MATERNO AS APELLIDO_MATERNO_MEDICO,
    M.ESPECIALIDAD,
    M.ESTADO AS ESTADO_MEDICO,
    U.USUARIO,
    P.NOMBRES AS NOMBRE_PACIENTE,
    P.APELLIDO_PATERNO AS APELLIDO_PATERNO_PACIENTE,
    P.APELLIDO_MATERNO AS APELLIDO_MATERNO_PACIENTE,
    P.TELEFONO,
    P.FECHA_NACIMIENTO,
    P.ESTADO AS ESTADO_PACIENTE,
	C.MOTIVO,
    C.DIAGNOSTICO,
    C.TRATAMIENTO,
    CT.FECHA_HORA,
    CT.TIPO_CITA
FROM CONSULTAS AS C
INNER JOIN CITAS AS CT
ON C.ID_CITA = CT.ID_CITA
INNER JOIN MEDICOS AS M
ON M.ID_MEDICO = CT.ID_MEDICO
INNER JOIN PACIENTES AS P
ON P.ID_PACIENTE = CT.ID_PACIENTE
INNER JOIN USUARIOS AS U
ON P.ID_PACIENTE = U.ID;