/*
	Vista que muestra todos los datos de
    los pacientes.
*/
CREATE VIEW DATOS_PACIENTE AS
SELECT
	U.ID,
    U.USUARIO,
    U.CONTRASENIA,
    P.NOMBRES,
    P.APELLIDO_PATERNO,
    P.APELLIDO_MATERNO,
    P.TELEFONO,
    P.FECHA_NACIMIENTO,
    P.ESTADO,
    D.COLONIA,
    D.CALLE,
    D.NUMERO
FROM PACIENTES AS P
INNER JOIN USUARIOS AS U
ON P.ID_PACIENTE = U.ID
INNER JOIN DIRECCIONES AS D
ON D.ID_PACIENTE = P.ID_PACIENTE;