/*
	Vista que muestra los datos del paciente, incluida sus datos
    de usuario y los datos asociados a su dirección.
*/
CREATE VIEW DATOS_PACIENTE AS
SELECT
	P.ID_PACIENTE AS ID,
    CONCAT(P.NOMBRES, " ", P.APELLIDO_PATERNO, " ", P.APELLIDO_MATERNO) AS NOMBRE_COMPLETO,
    P.TELEFONO,
    P.FECHA_NACIMIENTO,
    TIMESTAMPDIFF(YEAR, FECHA_NACIMIENTO, CURDATE()) AS EDAD,
    P.ESTADO,
    U.USUARIO AS CORREO_ELECTRONICO,
    U.CONTRASENIA,
    CONCAT(D.COLONIA, ", ", D.CALLE, ", #", D.NUMERO) AS DIRECCION
FROM PACIENTES AS P
INNER JOIN USUARIOS AS U
ON P.ID_PACIENTE = U.ID
INNER JOIN DIRECCIONES AS D
ON D.ID_PACIENTE = P.ID_PACIENTE;